create app : user, cars, provider, car_showroom, customer, discount
CeNTePeDe/show_room_app pull request #2
Opened 2023-04-16 16:08 UTC by CeNTePeDe

2023-04-17 13:35 UTC, slavadan commented
А название репы так и не поменяла)

2023-04-17 13:49 UTC, slavadan requested changes

2023-04-17 13:49 UTC, slavadan commented on show_room_app/Dockerfile
> +#COPY . /usr/src/app/
убери

2023-04-17 13:49 UTC, slavadan commented on show_room_app/car_showroom/admin.py
> +        "car_showroom", "number_of_car", "discount",
не по стандарту

2023-04-17 13:49 UTC, slavadan commented on show_room_app/cars/models.py
> +        max_length=1, choices=CHOICES_NUMBER_OF_DOORS, default="4"
а чо длина 1, а если в чойсе будет двухзначное число?

2023-04-17 13:49 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +        verbose_name="discount rate",
Может стоить добавить дату начала и дату конца скидки? И потом через проперти считает валидная скидка еще или нет

2023-04-17 13:49 UTC, slavadan commented on show_room_app/customer/models.py
> +    cars = models.ForeignKey('cars.Car', on_delete=models.CASCADE)
тут тоже можно json field

2023-04-17 13:49 UTC, slavadan commented on show_room_app/customer/models.py
> +    list_of_purchases = ArrayField(models.CharField(max_length=200), blank=True)
думаю вместо массива можно использовать fk на Transaction

2023-04-17 13:49 UTC, slavadan commented on show_room_app/discount/admin.py
> +admin.site.register(CarShowRoomDiscount)
Плохая админка

2023-04-17 13:49 UTC, slavadan commented on show_room_app/show_room_app/settings.py
> +    ALLOWED_HOSTS += [os.environ.get("ALLOWED_HOST")]
а пачему +=. И вместо списка используй кортежек

2023-04-17 13:49 UTC, slavadan commented on show_room_app/show_room_app/settings.py
> +load_dotenv()
а если файла нету

2023-04-17 13:49 UTC, slavadan commented on show_room_app/user/admin.py
> +# from user.models import User
а хде админка

2023-04-17 13:49 UTC, slavadan commented on show_room_app/start.sh
> +python manage.py runserver 0.0.0.0:8000
а конце всегда пустуя строка

2023-04-17 13:49 UTC, slavadan commented on show_room_app/user/models.py
> +# class User(AbstractUser):
а чего закомменчено

2023-04-17 14:46 UTC, CeNTePeDe commented on show_room_app/cars/models.py
> +        max_length=1, choices=CHOICES_NUMBER_OF_DOORS, default="4"
у меня заложено до 5дверей, так что больше 1 не будет)

2023-04-17 14:47 UTC, CeNTePeDe commented on show_room_app/customer/models.py
> +    cars = models.ForeignKey('cars.Car', on_delete=models.CASCADE)
по заданию, при создании offer покупатель задает максимальную цену и модель, поэтому я и навесила на машины FK

2023-04-17 14:49 UTC, CeNTePeDe commented on show_room_app/user/admin.py
> +# from user.models import User
дело в том, что данная схема не работает, тк нет никаких миграций, а все идет от  AbstractUser, поэтому и закаментчено

2023-04-17 14:50 UTC, CeNTePeDe commented on show_room_app/user/models.py
> +# class User(AbstractUser):
да, и связи никакой нет, ни к одной модели, может FK на каждую модель, Как  думаешь?

2023-04-17 17:01 UTC, slavadan commented on show_room_app/customer/models.py
> +    cars = models.ForeignKey('cars.Car', on_delete=models.CASCADE)
А если ему нужна машина конкретного цвета. FK тут не нужен

2023-04-17 17:02 UTC, slavadan commented on show_room_app/customer/models.py
> +    cars = models.ForeignKey('cars.Car', on_delete=models.CASCADE)
даже если делать по твоей логике можно напрямую обращаться к автосалонам
или car

2023-04-18 13:01 UTC, CeNTePeDe commented on show_room_app/customer/models.py
> +    cars = models.ForeignKey('cars.Car', on_delete=models.CASCADE)
покупатель создает Offer, указывая максимальную цену автомобиля и указывая автомобиль, которым он интересуется.  Затем Celery запускает скрипт, который по Offer пользователей по всем автосалонам ищет подходящие автомобили по наиболее выгодным ценам. -Это из задания, с этого и логика, там же с каждым автомобилем будет и цвет и тд

2023-04-19 06:33 UTC, slavadan commented on show_room_app/customer/models.py
> +    cars = models.ForeignKey('cars.Car', on_delete=models.CASCADE)
Так а фк тут зачем?

2023-04-19 06:34 UTC, slavadan commented on show_room_app/customer/models.py
> +    cars = models.ForeignKey('cars.Car', on_delete=models.CASCADE)
Ты будешь искать эти машины через фк?

2023-04-19 06:35 UTC, slavadan commented on show_room_app/user/models.py
> +# class User(AbstractUser):
не понял

2023-04-19 06:39 UTC, slavadan commented on show_room_app/customer/models.py
> +    cars = models.ForeignKey('cars.Car', on_delete=models.CASCADE)
Вот представь ты покупатель и хочешь купить себе машину. Ты залетаешь на сайт в свой кабинет(админка). Потом же ты заходишь в раздел с машинами и смотришь себе машину. Или ты всетаки заходишь в раздел с покупателями и пытаешь достать машину через fk(хотя я себе это как-то слабо представляю)

2023-04-19 06:43 UTC, slavadan commented on show_room_app/customer/models.py
> +    cars = models.ForeignKey('cars.Car', on_delete=models.CASCADE)
и дергать каждый раз модель автомобиля через связь от клиента, как-то затратно получается. Плюс тебе нужно будет выбирать объект самого автомобиля и дергать его характеристики, чтобы купить другой объект автомобиля?

2023-04-20 17:41 UTC, closed without merging