fix Admin Pannel, create Abstract class , create Serilizer for app car
CeNTePeDe/show_room_app pull request #3
Opened 2023-04-20 17:43 UTC by CeNTePeDe

2023-04-20 18:24 UTC, slavadan requested changes
Я так на глаз накидал. Завтра мб подробнее посмотрим

2023-04-20 18:24 UTC, slavadan commented on show_room_app/car_showroom/admin.py
> +    )
можно подобавлять read only fields. Например id не должен изменяться из админки. По такойжу логике подабавляй другие поля в этой и других классах

2023-04-20 18:24 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +class BaseRole(models.Model):
а почему название BaseRole?

2023-04-20 18:24 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +    country = CountryField(default="Russia", blank=False)
Возможно, balnk=False тут лишний. Потом решим

2023-04-20 18:24 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +
нету док стринки. И из названия может быть не понятно для чего модель. Наприме BaseModel хорошее название тк сразу понятно, что на основе данной модели будут построены другие модели. Думаю нужно придумать другое название.

2023-04-20 18:24 UTC, slavadan commented on show_room_app/show_room_app/settings.py
> +load_dotenv()
А если файла не будет? То что будет происходить. Оно просто ничего не добавит? Или вызовется exception?

2023-04-21 15:21 UTC, slavadan requested changes

2023-04-21 15:21 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +        total_price = float((price * self.discount_rate) / 100)
Никогда не используй  Float для денежных расчетов https://coderlessons.com/articles/java/pochemu-vy-nikogda-ne-dolzhny-ispolzovat-float-i-double-dlia-denezhnykh-raschetov

2023-04-21 15:21 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +        total_price = float((price * self.discount_rate) / 100)
используй Decimal

2023-04-21 15:21 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +        total_price = float((price * self.discount_rate) / 100)
Зачем вообще get_price в скидках?

2023-04-21 15:21 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +        total_price = float((price * self.discount_rate) / 100)
стоймость же будет считаться в селеру таске

2023-04-21 15:21 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +    discount_rate = models.IntegerField(
Лучше использовать PositiveIntegerField

2023-04-21 15:21 UTC, slavadan commented on show_room_app/cars/admin.py
> +    list_filter = ("name", "model_car")
Лучше показывать так кортеж ("name", "model_car",)

2023-04-21 15:21 UTC, slavadan commented on show_room_app/core/abstract_models.py
>  class MiddleModel(models.Model):
rename  таблицу

2023-04-21 15:21 UTC, slavadan commented on show_room_app/discount/models.py
> +    discount_rate = models.IntegerField(
тоже что и сверху

2023-04-21 15:35 UTC, slavadan requested changes

2023-04-21 15:35 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +class MiddleModel(models.Model):
Переименую модель, чтобы можно понять зачем её замешивать в другую модель, представь что ты не писала такую и видишь такое названи. Хотела бы такую модельку подмешивать?

2023-04-21 15:35 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +    margin = models.IntegerField(
позитив филд

2023-04-21 15:35 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +    number_of_cars = models.IntegerField(
позитив филд

2023-04-21 15:35 UTC, slavadan commented on show_room_app/core/abstract_models.py
> +        return total_price
а в чем прикол total_price. и get_price в акциях?

2023-04-21 15:35 UTC, slavadan commented on show_room_app/core/validators_show_room.py
> +    if value in range(1950, datetime.now().year + 1):
я провтыкал. А почему ты к текущему году бобавляешь + 1)))

2023-04-21 15:35 UTC, slavadan commented on show_room_app/customer/admin.py
> +    readonly_fields = ("date",)
тут можно id добавить. Кстати если это дата создания, то окей. А если нет то поменяй

2023-04-21 15:35 UTC, slavadan commented on show_room_app/customer/admin.py
> +    list_display = ("car_showroom", "price", "discount", "date")
Ставь запятые после последнего элемента в кортежах.

2023-04-21 15:35 UTC, slavadan commented on show_room_app/customer/models.py
> +    )
надо что-то с этим придумать

2023-04-21 15:35 UTC, slavadan commented on show_room_app/discount/models.py
> +            return price
короче полную сумму давай лучше считать в celery задаче, а то ты поплывешь в этих функциях

2023-04-21 15:39 UTC, slavadan commented on show_room_app/core/validators_show_room.py
> +    if value in range(1950, datetime.now().year + 1):
Это кстати вообще фигня какая-то. Получается, что создаешь список примерно из 70 чисел. Потом через in по нему проходишься. Разве не проще сравнить?

2023-04-22 12:43 UTC, CeNTePeDe commented on show_room_app/core/validators_show_room.py
> +    if value in range(1950, datetime.now().year + 1):
С чем сравнить, мне нужен только год, а +1 потому что range не включает последний год

2023-04-22 13:03 UTC, CeNTePeDe commented on show_room_app/customer/models.py
> +    )
а именно, в каком направлении думать, название или реализация

2023-04-22 14:35 UTC, closed without merging