created api for app
CeNTePeDe/show_room_app pull request #5
Opened 2023-04-29 13:33 UTC by CeNTePeDe

2023-05-03 09:01 UTC, slavadan requested changes

2023-05-03 09:01 UTC, slavadan commented on show_room_app/user/managers.py
> +        ):
not extra_fields.get("is_car_showroom")

2023-05-03 09:01 UTC, slavadan commented on show_room_app/user/managers.py
> +            raise ValueError(_("Superuser must have is_superuser=True."))
not extra_fields.get("is_staff")

2023-05-03 09:01 UTC, slavadan commented on show_room_app/provider/views.py
> +        serializer = ProviderDetailSerializer(provider)
ты сделала `serializer_class`, а толку от него, если ты делаешь:  `serializer = ProviderDetailSerializer(provider)`

2023-05-03 09:01 UTC, slavadan commented on show_room_app/provider/views.py
> +        serializer = ProviderDetailSerializer(provider)
не гибко получается

2023-05-03 09:01 UTC, slavadan commented on show_room_app/provider/models.py
> +    user = models.OneToOneField("user.User", on_delete=models.CASCADE, primary_key=True)
related_name прокинь

2023-05-03 09:01 UTC, slavadan commented on show_room_app/discount/views.py
> +    permission_classes = [IsAdminUserOrReadOnly]
а @action так и не сделала((((

2023-05-03 09:01 UTC, slavadan commented on show_room_app/discount/views.py
> +        serializer = SeasonDiscountSerializer(season_discount)
ты сделала serializer_class, а толку от него

2023-05-03 09:01 UTC, slavadan commented on show_room_app/customer/views.py
> +        return Response(serializer.data)
а чего ты list переопределила?

2023-05-03 09:01 UTC, slavadan commented on show_room_app/user/permission.py
> +        return False
можно сделать одной строкой

2023-05-03 09:01 UTC, slavadan commented on show_room_app/user/permission.py
> +        return bool(request.method in permissions.SAFE_METHODS or request.user and request.user.is_staff)
а bool тут зачем?

2023-05-03 09:01 UTC, slavadan commented on show_room_app/user/permission.py
> +        return False
можно сделать одной строкой

2023-05-03 09:01 UTC, slavadan commented on show_room_app/user/permission.py
> +        return bool(request.method in permissions.SAFE_METHODS or request.user and request.user.is_staff)
bool тут не нужен

2023-05-03 09:01 UTC, slavadan commented on show_room_app/user/permission.py
> +        return False
одной строкой можно

2023-05-03 09:01 UTC, slavadan commented on show_room_app/user/serializer.py
> +    password2 = serializers.CharField(required=True, write_only=True)
password1 password2??

никогда не используй цифры в названии переменных

2023-05-03 09:01 UTC, slavadan commented on show_room_app/user/permission.py
> +        return bool(request.method in permissions.SAFE_METHODS or request.user and request.user.is_staff)
bool не нужен

2023-05-03 09:01 UTC, slavadan commented on show_room_app/provider/views.py
> +        provider = get_object_or_404(queryset, pk=pk)
ты же вкурсе, что `get_object_or_404` делает raise? И если не обрабатывать его твое приложение ляжет. Когда объекта нету, просто возвращай 404 в респосе

2023-05-03 09:01 UTC, slavadan commented on show_room_app/provider/views.py
> +        serializer = ProviderSerializer(queryset, many=True)
у тебя есть serializer_class

2023-05-03 09:01 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +        car_showroom = get_object_or_404(queryset, pk=pk)
читай ниже

2023-05-03 09:01 UTC, slavadan commented on show_room_app/car_showroom/models.py
> +    user = models.OneToOneField("user.User", on_delete=models.CASCADE, primary_key=True)
прокинь related_name или как там его

2023-05-03 09:01 UTC, slavadan commented
Добавь тайпхинты в функции

2023-05-05 17:58 UTC, slavadan requested changes

2023-05-05 17:58 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +    )
Что то сложно. Почему ты два раза prefetch_related вызываешь вместо, того чтобы  через запятую в одном прокинуть.

2023-05-05 17:58 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +    )
так же еще можно переопределить get_queryset или как там его. Тож можешь потрогать

2023-05-05 17:58 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +    )
емае

2023-05-05 17:58 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +    )
Ну ты нашаманила)))

2023-05-05 17:58 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +    )
словил передоз префетчей

2023-05-05 17:58 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +    )
Отмечу, что если ты никак не дергаешь связанную модель(что-то наподобии model1.model2.name = 'anime'), то смысла делать префетчи и селекты нету.

2023-05-05 17:58 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +    )
а зачем .all в конце

2023-05-05 17:58 UTC, slavadan commented on show_room_app/cars/views.py
> +    http_method_names = ["get", "post", "patch", "delete"]
прикольно, не знал, что так можно

2023-05-05 17:58 UTC, slavadan commented on show_room_app/cars/views.py
> +        unpublished = Car.objects.filter(is_active=False)
не понял, а почему unpublished_cars?

2023-05-05 17:58 UTC, slavadan commented on show_room_app/cars/views.py
> +        unpublished = Car.objects.filter(is_active=False)
есть какие-то published cars? чето не то с неймингом

2023-05-05 17:58 UTC, slavadan commented on show_room_app/customer/views.py
> +        Prefetch('discount', queryset=CarShowRoomDiscount.objects.all().only('discount_name'))).all()
больше префетчей - богу префетчей

2023-05-05 17:58 UTC, slavadan commented on show_room_app/discount/views.py
> +        serializer = SeasonDiscountSerializer(season_discount)
Ты не поправила. Когда ты делаешь `serializer = SeasonDiscountSerializer(season_discount)` смысл от `serializer_class = SeasonDiscountSerializer` теряется. Те тут нужно `serializer = serializer_class(season_discount)`.
В других местах тоже поменяй

2023-05-05 17:58 UTC, slavadan commented on show_room_app/discount/views.py
> +        serializer = ProviderDiscountSerializer(provider_discount)
уже писал выше

2023-05-05 17:58 UTC, slavadan commented on show_room_app/discount/views.py
> +        serializer = ProviderDiscountSerializer(car_showroom_discount)
уже писал выше

2023-05-05 17:58 UTC, slavadan commented on show_room_app/provider/views.py
> +        .filter(is_active=True)
уххх опять префетчи

2023-05-05 17:58 UTC, slavadan commented on show_room_app/provider/views.py
> +        ).all()
префетчи

2023-05-05 17:58 UTC, slavadan commented on show_room_app/show_room_app/settings.py
> +    ]
Впервые такое вижу

2023-05-05 17:58 UTC, slavadan commented on show_room_app/show_room_app/settings.py
> +    ]
пояснительную бригаду пожалуйста

2023-05-05 17:58 UTC, slavadan commented on show_room_app/show_room_app/urls.py
>  router.register(r"season_discount", SeasonDiscountView, basename="season_discount")
Роуты кстати можно по апкам разбить и сюда докидывать. Если не поняла пиши в тг

2023-05-05 17:58 UTC, slavadan commented on show_room_app/show_room_app/urls.py
>  router.register(r"season_discount", SeasonDiscountView, basename="season_discount")
посмотри какие роуты кроме DefaultRouter есть

2023-05-05 17:58 UTC, slavadan commented on show_room_app/user/managers.py
> +            or not extra_fields.get("is_provider") is not True
тип если не False/True это не True. Каламбур какой-то. Вместо `not extra_fields.get("is_customer") is not True` можно просто `not extra_fields.get("is_customer")` ну или если прям хочется `extra_fields.get("is_customer") is False` ну или `extra_fields.get("is_customer") == False`. Если что-то не поняла насчет `not extra_fields.get("is_customer")`. И почитай какие есть варианты conditions, а то не понятно и не читаемо.

2023-05-05 17:58 UTC, slavadan commented on show_room_app/user/managers.py
> +        if not extra_fields.get("is_staff") is not True:
тоже самое

2023-05-05 17:58 UTC, slavadan commented on show_room_app/user/managers.py
> +        if not extra_fields.get("is_superuser") is not True:
тоже самое

2023-05-05 17:58 UTC, slavadan commented on show_room_app/user/permission.py
> +        )
это у тебя форматтер так сделал? если нет то сделай в одну линию

2023-05-05 17:58 UTC, slavadan commented on show_room_app/user/permission.py
> +        ) or request.user.is_superuser:
ты немного не поняла. зачем тут if? можно же просто `return (obj.user == request.user and request.user.is_customer) or request.user.is_superuser`. Насчет тайпхинтов: request вообще-то имеет тип HttpRequest.

2023-05-05 17:58 UTC, slavadan commented on show_room_app/user/permission.py
> -        return False
аналогично

2023-05-05 17:58 UTC, slavadan commented on show_room_app/user/permission.py
> +        ) or request.user.is_superuser:
аналогично

2023-05-05 17:58 UTC, slavadan commented on show_room_app/user/serializer.py
> +    password_confirm = serializers.CharField(required=True, write_only=True)
другое дело)

2023-05-05 17:58 UTC, slavadan commented on show_room_app/user/serializer.py
> -            "is_active",
а чего ты is_active убрала?

2023-05-05 17:58 UTC, slavadan commented on show_room_app/user/views.py
> +        serializer = UserSerializer(car)
про сериализаторы писал выше.

2023-05-05 18:26 UTC, slavadan commented on show_room_app/cars/views.py
> +        unpublished = Car.objects.filter(is_active=False)
достаточно будет get_cars или car_list

2023-05-06 16:26 UTC, CeNTePeDe commented on show_room_app/cars/views.py
> +        unpublished = Car.objects.filter(is_active=False)
Это я репетировала action, это только для админа неактивные машины, те они в базе есть , но не опубликованы

2023-05-06 16:28 UTC, CeNTePeDe commented on show_room_app/user/views.py
> +        serializer = UserSerializer(car)
Вы же со Всеволодом по этому поводу спорили, и сказали, что так и надо только импорт из generics импортировать

2023-05-06 16:29 UTC, CeNTePeDe commented on show_room_app/user/permission.py
> +        )
Форматтер возращает

2023-05-09 16:23 UTC, slavadan requested changes

2023-05-09 16:23 UTC, slavadan commented on show_room_app/car_showroom/models.py
> +        related_name="CarShowRoom",
Не заметил. CarShowRoom это будет название переменной у класса юзер. А как ты понимаешь CarShowRoom в таком стиле переменные не называют. CarShowRoom -> car_showroom

2023-05-09 16:23 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +        )
два префетча

2023-05-09 16:23 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +    ).all()
все еще не понимаю зачем тебе .all

2023-05-09 16:23 UTC, slavadan commented on show_room_app/cars/permission.py
> +        )
не исправила

2023-05-09 16:23 UTC, slavadan commented on show_room_app/cars/views.py
> +        unpublished = Car.objects.filter(is_active=False)
так и не переименовала

2023-05-09 16:23 UTC, slavadan commented on show_room_app/provider/urls.py
> +]
я мб уже не помню, но вроде можно делать так: urlpatterns = router.urls
если можно то поменяй тут и в других местах

2023-05-15 10:53 UTC, slavadan requested changes

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/test_serializer.py
> +    print("expected_json=", expected_json)
принтов в тестах не должно быть

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/test_serializer.py
> +pytestmark = pytest.mark.django_db
переделай с использование декоратора

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/test_serializer.py
> +    car = CarFakeFactory.create()
Ты тестируешь и API и сериализатор для Car в одном файле и при этом у тебя файл называется test_serializer???????!!!!! Я же вроде показывал и рассказывал про нейминг и структуру тестов по принципу
один файл - одна сущность. Те у тебя папка tests в ней __init__.py, conftest.py, factory.py
У тебя есть модель Car. значит файлик будет называться test_car.py. Также можно еще больше разделить в том плане чтобы не тестировать все сразу в одном файле можно сделать папку test_api например и в ней будет test_car.py и тестить апи для модели Car в этом файле, а для другого например test_model и в ней тоже будет test_car.py и тестировать модели или какую нибудь бизнес логику связанную с моделями car(но это не обязательно - главное чтобы ты смысл поняла).

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/factories.py
> +fake.add_provider(VehicleProvider)
если ты используешь factory-boy, то и используй пожайлуста faker который он предоставляет)

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/factories.py
> +    is_active = True
в чем прикол двух фабрик для машины. Одной мало?

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/factories.py
> +    is_active = True
мощности фабрики не хватает чтоле Xd?

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/test_model.py
> +    assert car.is_active == True
на фикстуры тесты не пишутся

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/test_serializer.py
> +pytestmark = pytest.mark.django_db
в других местах тоже

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/factories.py
> +fake.add_provider(VehicleProvider)
переделай в других местах тоже

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/test_serializer.py
> +    assert json.loads(response.content)["price"] == str(car.price.amount)
Ну емае как так можно. Я очень сильно расстроен. Как думаешь почему?

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/test_serializer.py
> +    assert json.loads(response.content)["price"] == str(car.price.amount)
Моя печаль не знает границ

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/test_serializer.py
> +    assert json.loads(response.content)["price"] == str(car.price.amount)
жду ответ в тг

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/test_serializer.py
> +    car = CarFakeFactory.build()
Посмотри как делают фикстуры как фабричный метод и сделай также. В других местах тоже

2023-05-15 10:53 UTC, slavadan commented on show_room_app/discount/tests/conftest.py
> +register(CarShowRoomDiscountFactory)
кстати я не помню зачем нужен register. Но если сделаешь фабричный метод то register тут не нужен будет

2023-05-15 10:53 UTC, slavadan commented on show_room_app/discount/tests/test_provider_discount.py
> +    assert json.loads(response.content) == new_provider_discount
Выглядит вроде неплохо, но есть принт в печаль в одном месте

2023-05-15 10:53 UTC, slavadan commented on show_room_app/cars/tests/test_serializer.py
> +    car = CarFakeFactory.build()
Можно конечно и так оставить, но тогда ты не узнаешь что из фикстуры можно устроить фабричный метод, в которую можно доп логику прописывать. Мб покажу завтра пример

2023-05-15 10:53 UTC, slavadan commented on show_room_app/discount/tests/test_car_showroom_discount.py
> +    print(new_car_showroom_discount)
принты

2023-05-15 10:53 UTC, slavadan commented on show_room_app/user/tests/test_user.py
> +    data = response.data
опа, а тут я удивлен. А че раньше так нельзя было?

2023-05-15 10:53 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +        return Response(status=status.HTTP_403_FORBIDDEN)
у тебя же пермишен стоит. зачем тут if

2023-05-15 18:46 UTC, CeNTePeDe commented on show_room_app/cars/tests/test_car.py
> +def test_update_car(client):
Все тесты на  update не срабатывают, выскакивает ошибка 405

2023-05-15 18:48 UTC, CeNTePeDe commented on show_room_app/car_showroom/tests/test_car_showroom.py
> +
тут с этим тоже проблемы, badrequest((((

2023-05-19 09:25 UTC, slavadan requested changes

2023-05-19 09:25 UTC, slavadan commented on show_room_app/car_showroom/views.py
> +    #     return Response(status=status.HTTP_403_FORBIDDEN)
?

2023-05-19 09:25 UTC, slavadan commented on show_room_app/car_showroom/tests/conftest.py
> +
я вроде говорил перенести переменные в kwargs функции build. в других местах тоже

2023-05-19 09:25 UTC, slavadan commented on show_room_app/car_showroom/tests/factories.py
> +faker = Faker()
Про попробовать использовать Facker из factory-boy я тоже говорил. И не нужно будет объявлять переменные faker = Faker().
https://besnard-consulting.com/articles/django-testing/3-generating-random-datasets-with-factory-boy

в других местах тоже

2023-05-19 09:25 UTC, slavadan commented on show_room_app/car_showroom/tests/test_car_showroom.py
> +    print(payload)
не убрала print

2023-05-19 09:25 UTC, slavadan commented on show_room_app/cars/tests/test_car.py
> +    assert payload["is_active"] == data["is_active"]
Кстати на одном из ревью на моем проекте было рассказано про методологию написания тестов AAA(Arrange, Act, Assert). Почитай это очень интересно https://habr.com/ru/articles/507594/. И сделай также те Раздели отступами .(Arrange, Act, Assert). Если не понятно пиши в тг

2023-05-19 09:25 UTC, slavadan commented on show_room_app/user/serializer.py
> +    password2 = serializers.CharField(write_only=True, required=True)
случайно увидел, но про наличие цифр в названии переменных я уже говорил!!!

2023-05-22 13:47 UTC, CeNTePeDe commented on show_room_app/car_showroom/serializer.py
смотри, может здесь все таки по id , просто модель связующая, и информация только для провайдера, а уже какие модели машины, провайдер может и запросом провести

2023-05-22 13:48 UTC, CeNTePeDe commented on show_room_app/car_showroom/tests/conftest.py
>      def car_showroom(**kwargs):
вот здесь убрала create_user, тк мы прокидываем в ручную

2023-05-22 13:50 UTC, CeNTePeDe commented on show_room_app/customer/models.py
>      price = MoneyField(max_digits=14, decimal_places=2, default_currency="USD")
сustomer я все таки добавила в transaction

2023-05-22 13:51 UTC, CeNTePeDe commented on show_room_app/customer/models.py
>      price = MoneyField(max_digits=14, decimal_places=2, default_currency="USD")
transaction test еще не переделывала

2023-05-22 13:52 UTC, CeNTePeDe commented on show_room_app/car_showroom/serializer.py
ну и sellmodel по такому же принципу?

2023-05-22 13:58 UTC, CeNTePeDe commented on show_room_app/customer/models.py
>      price = MoneyField(max_digits=14, decimal_places=2, default_currency="USD")
я бы еще кинула может fk на машину, чтобы знать что за она

2023-05-23 19:10 UTC, CeNTePeDe commented on show_room_app/car_showroom/serializer.py
> +    #
Метод оставлен на всякий случай, )))

2023-05-23 19:11 UTC, CeNTePeDe commented on show_room_app/car_showroom/serializer.py
> +    #
Вторая модель сделана по id

2023-05-23 19:15 UTC, CeNTePeDe commented on show_room_app/customer/models.py
> +    )
я, конечно, кинула связь на transaction, НО как все таки работает FK , с какой стороны MANY а с какой ONE, по такой логике и на CarShowRoom надо разворачивать связь

2023-05-23 19:19 UTC, CeNTePeDe commented on show_room_app/customer/tests/test_transaction.py
> +
Вот здесь по ID, просто по отдельности мы же проверяем (создание машины, custoner, car_showroom и тд), в этой модельке мы просто собираем все данные по существующим объектам и высчитываем цену автомобиля, на не надо их создавать мы просто их собираем вместе

2023-06-14 10:52 UTC, closed without merging